# Versão do Python que vamos usar
FROM python:3.9

# Definindo o diretório de trabalho no contêiner
WORKDIR /app

# Copia o arquivo com as dependências para dentro do conteiner
COPY requirements.txt

# Instalando as dependencias do python no conteiner
RUN pip install --no-cache-dir -r requirements.txt

# Copia o conteúdo do diretório atual para o diretório de trabalho no contêiner 
COPY . .

# Expondo a porta em que a aplicação irá rodar
EXPONSE 5000

# Comando para rodar a aplicação
CMD ["python", "app/main.py"]
